/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import omahahelp.cards.Card;
import omahahelp.cards.Deck;
import omahahelp.cards.PlayersCards;
import omahahelp.compare.Compare;
import omahahelp.compare.Values;

/**
 *
 * @author petteri
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ownCard1 = new javax.swing.JTextField();
        enemysCard1 = new javax.swing.JTextField();
        countOdds = new javax.swing.JButton();
        ownCard2 = new javax.swing.JTextField();
        enemysCard2 = new javax.swing.JTextField();
        instructionsToSetCards = new javax.swing.JLabel();
        modelOfCard1 = new javax.swing.JLabel();
        modelOfCard2 = new javax.swing.JLabel();
        modelOfCard3 = new javax.swing.JLabel();
        modelOfCard4 = new javax.swing.JLabel();
        ownWins = new javax.swing.JLabel();
        ties = new javax.swing.JLabel();
        enemysWins = new javax.swing.JLabel();
        turnBox = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ownCard1.setText("2 of HEARTS");
        ownCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownCard1ActionPerformed(evt);
            }
        });

        enemysCard1.setText("2 of DIAMONDS");

        countOdds.setText("Näytä suhteet flopin jälkeen");
        countOdds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countOddsActionPerformed(evt);
            }
        });

        ownCard2.setText("2 of SPADES");
        ownCard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownCard2ActionPerformed(evt);
            }
        });

        enemysCard2.setText("2 of CLUBS");

        instructionsToSetCards.setText("Aseta kortit muodossa \"x of SUIT\". ( x = 2-14) (SUIT  = HEARTS/DIAMONDS/CLUBS/SPADES)  ");

        modelOfCard1.setText("Vastus(x of SUIT)");

        modelOfCard2.setText("Korttisi (x of SUIT)");

        modelOfCard3.setText("Korttisi (x of SUIT)");

        modelOfCard4.setText("Vastus(x of SUIT)");

        ownWins.setText("Voittosi ");

        ties.setText("Tasurit");

        enemysWins.setText("Vastustajan voitot");

        turnBox.setText("turnin jälkeen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countOdds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructionsToSetCards)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(ownWins, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ties, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enemysWins, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ownCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemysCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemysCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelOfCard3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelOfCard2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelOfCard1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelOfCard4)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turnBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enemysCard1, enemysCard2, modelOfCard1, modelOfCard2, modelOfCard3, modelOfCard4, ownCard1, ownCard2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {enemysWins, ownWins, ties});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionsToSetCards, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelOfCard1)
                    .addComponent(modelOfCard2)
                    .addComponent(modelOfCard3)
                    .addComponent(modelOfCard4))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemysCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enemysCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(turnBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countOdds)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownWins, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ties)
                    .addComponent(enemysWins, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {enemysWins, ownWins, ties});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ownCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownCard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownCard1ActionPerformed

    private void ownCard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownCard2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownCard2ActionPerformed

    private void countOddsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countOddsActionPerformed
        // TODO add your handling code here:
        Deck deck = new Deck();
        deck.addCards();

        String cardA = ownCard1.getText();
        String cardB = ownCard2.getText();
        String cardC = enemysCard1.getText();
        String cardD = enemysCard2.getText();
        Card a = deck.getCardByString(cardA);
        Card b = deck.getCardByString(cardB);
        Card c = deck.getCardByString(cardC);
        Card d = deck.getCardByString(cardD);
        PlayersCards handA = new PlayersCards(deck, a, b);
        PlayersCards handB = new PlayersCards(deck, c, d);
        Compare compare = new Compare(handA, handB, deck);

        if (!turnBox.isSelected()) {
            compare.addWinsAndCardsToHashMaps(deck, true, false);
            ownWins.setText("Voittosi: " + compare.getAwins() + "/" + compare.getMap().size());
            ties.setText("Tasurit: " + compare.getTies() + "/" + compare.getMap().size());
            enemysWins.setText("Vastustajan voitot:" + compare.getbWins() + "/" + compare.getMap().size());
        }

        if (turnBox.isSelected()) {
            compare.addWinsAndCardsToHashMaps(deck, false, true);
            compare.calculateTurn();
            ownWins.setText("Voittosi: " + compare.getAwins() + "/" + compare.getTurns().size());
            ties.setText("Tasurit: " + compare.getTies() + "/" + compare.getTurns().size());
            enemysWins.setText("Vastustajan voitot:" + compare.getbWins() + "/" + compare.getTurns().size());
        }

    }//GEN-LAST:event_countOddsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countOdds;
    private javax.swing.JTextField enemysCard1;
    private javax.swing.JTextField enemysCard2;
    private javax.swing.JLabel enemysWins;
    private javax.swing.JLabel instructionsToSetCards;
    private javax.swing.JLabel modelOfCard1;
    private javax.swing.JLabel modelOfCard2;
    private javax.swing.JLabel modelOfCard3;
    private javax.swing.JLabel modelOfCard4;
    private javax.swing.JTextField ownCard1;
    private javax.swing.JTextField ownCard2;
    private javax.swing.JLabel ownWins;
    private javax.swing.JLabel ties;
    private javax.swing.JRadioButton turnBox;
    // End of variables declaration//GEN-END:variables
}
